### ISSUE TITLE
Credentials AWS

### ISSUE THREAD

**Issue by katze** [jessicakuijer/ai-chatbot-ChatGPT#1]
Bonjour et merci pour d'avoir partagé ce projet.
Attention cependant a ne pas commiter vos credentials AWS

https://github.com/jessicakuijer/ai-chatbot-ChatGPT/blob/e13b82846e8a3da206b5e0d8acb7c1480df69240/.env#L33

--
Michael

**Comment by jessicakuijer** [comment]
merci c'est gentil, je ne sais meme pas ce que ça faisait la car je n'ai pas de base de données la bas.

**Comment by katze** [comment]
c'est la base utilisée par https://ai-chatbot.herokuapp.com/

**Comment by jessicakuijer** [comment]
Non justement:)
Donc pas d'impact car cette ligne était obsolète mais merci pour me l'avoir souligné
